spring:
  application:
    name: SpringAiCode

  ai:
    openai:
      api-key: ${spring-ai-demo}

      embedding:
        options:
          model: text-embedding-3-large

    vectorstore:
      redis:
        index-name: product-index
        prefix: product
        initialize-schema: true
        distance-metric: COSINE
        vector-algorithm: HNSW

  data:
    redis:
      host: localhost
      port: 6379

  main:
    allow-bean-definition-overriding: true

  sql:
    init:
      schema-locations: classpath:init/schema.sql
      mode: always