spring:
  application:
    name: SpringAiCode

  ai:
    openai:
      api-key: ${spring-ai-demo}
    vectorstore:
      redis:
        index-name: product-index
        prefix: product
        initialize-schema: true
        distance-metric: COSINE
        vector-algorithm: HNSW

  data:
    redis:
      host: localhost
      port: 6379
#  datasource:
#    url: jdbc:postgresql://localhost:5432/suhail
#    username: postgres
#    password: suhail
#    driver-class-name: org.postgresql.Driver
#
  main:
    allow-bean-definition-overriding: true
#
#  jpa:
#    show-sql: true

  sql:
    init:
      schema-locations: classpath:init/schema.sql
      mode: always